config/routes.rb
Dailythreads::Application.routes.draw do
  get "admin" => 'admin#index'
  get "index" => 'store#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  get "store/sunglasses"

  get "store/shirts"

  get "store/shoes"

  get "store/belts"

  get "store/watches"

  get "store/pants"

  get "store/underwear"

  get "store/hats"

  resources :line_items

  match "line_items/decrement", :to=> 'line_items#decrement', :via => :post

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', as: 'store'

end

app/models/cart.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class Cart < ActiveRecord::Base
  attr_accessible :product_id, :product
  has_many :line_items, dependent: :destroy


  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  
  # GET /carts
  # GET /carts.json
  def index
    @cart = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html
      format.js
      format.json { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
	<div class="container-fluid">
		<div class="row" style="position:fixed; height: 2em; background-color: black;">
			<div class="span">
				<h4><i class="icon-shopping-cart icon-white"></i> Your Cart&nbsp;&nbsp;&nbsp;</h4>
			</div>
			
      <div class="pull-right"><a class="btn btn-mini" data-toggle="modal" href="#myModal2" ><i class="icon-white icon-zoom-in"></i> Detail</a>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to cart, :class => "btn-mini btn", method: :delete, :"data-toggle" => "modal", :href => "#myModal", :remote => "true" do %>
			        <%= content_tag :i, :class => "icon-remove icon-white" do %>
			        <% end %>
			        Delete
			    <% end %>
			</div>
		</div>
    <br>
    <br>
			<%= render(cart.line_items.order(:created_at)) %>
			<div class="row" style="margin-left:10px; border-top: 1px dotted white; margin-top: 6px;">
				<div class="span1">Total</div>
				<div class=""><%= number_to_currency(cart.total_price) %></div>
			</div>
		<div class="row">
      <!-- <div class="span1 offset1">
        <a class="btn " data-toggle="modal" href="#myModal2" >Detail</a>
      </div> -->
			<div class="offset2"><%= button_to 'Checkout', new_order_path, method: :get, id:"checkout-button", class: "btn btn-primary" %>
			</div>
		</div>
		 <div id="modal">
       <div id="myModal" class="modal hide">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>Are You Sure You Want To Delete Your Cart?</h3>
          </div>
          <div class="modal-footer">
            <%= link_to cart, :class => "btn pull-left btn-primary", :remote => "true", method: :delete, :"data-dismiss" => "modal" do %>
                      Delete  
              <%= content_tag :i, :class => "icon-trash icon-white" do %>
              <% end %>
              <a href="#" class="btn pull-left" data-dismiss="modal" >Cancel</a>
            <% end %>
          </div>
       </div>
     </div>
       <div id="modal2">
       <div id="myModal2" class="modal hide">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>Your Cart:</h3>
          </div>
          <div class="modal-body">
            <%= render(cart.line_items.order(:created_at)) %>
          </div>
          <div class="modal-footer">
              <a href="#" class="btn pull-left" data-dismiss="modal" >Close</a>
            <%= link_to cart, :class => "btn-mini btn", method: :delete, :"data-toggle" => "modal", :"data-dismiss" => "modal", :href => "#myModal", :remote => "true" do %>
              <%= content_tag :i, :class => "icon-remove icon-white" do %>
              <% end %>
              Delete
          <% end %>
          </div>
       </div>
	</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$('#cart').html("<%=j render @cart %>");

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>